import Header from './components/Layout/Header'
import Footer from './components/Layout/Footer'
import "bootstrap/dist/css/bootstrap.min.css"
import './styles/globals.scss'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>

    </html>
  )
}
