import Header from './components/Layout/Header'
import Footer from './components/Layout/Footer'
import "bootstrap/dist/css/bootstrap.min.css"
import { HookProvider } from './Hooks/Hook'
import { getCurrency } from './libs/newsData'
import './styles/globals.scss'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {

  const currency = await getCurrency()

  return (
    <html lang="az">
      <HookProvider>
        <body>
          <div className='overlay'></div>
          <Header currency={currency} />
          {children}
          <Footer />
        </body>
      </HookProvider>
    </html>
  )
}
